"""Game rules. Pure and deterministic: no I/O, no globals, seeded rng."""

from engine.models import (
    DIRECTION_VECTORS,
    Action,
    Contact,
    ContactKind,
    Coord,
    Detonation,
    Direction,
    Emission,
    EmissionKind,
    Fire,
    GameState,
    Move,
    Outcome,
    Ping,
    PlayerId,
    RangeBucket,
    RoundEvents,
    RoundResult,
    RunSilent,
    ShipState,
)
from engine.placement import new_match, place_ships
from engine.resolve import resign, resolve
from engine.validation import InvalidAction, validate_action

__all__ = [
    "DIRECTION_VECTORS",
    "Action",
    "Contact",
    "ContactKind",
    "Coord",
    "Detonation",
    "Direction",
    "Emission",
    "EmissionKind",
    "Fire",
    "GameState",
    "InvalidAction",
    "Move",
    "Outcome",
    "Ping",
    "PlayerId",
    "RangeBucket",
    "RoundEvents",
    "RoundResult",
    "RunSilent",
    "ShipState",
    "new_match",
    "place_ships",
    "resign",
    "resolve",
    "validate_action",
]
